AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  UseCache: true
  NewCops: enable

  Exclude:
    - bin/**/*
    - vendor/**/*
    - Guardfile
    - lib/tasks/cucumber.rake
    - node_modules/**/*
    - tmp/**/*
    - db/*schema.rb
    - config.ru
    - config/environments/**/*
    - config/puma.rb
    - config/spring.rb

Gemspec/RequiredRubyVersion:
  Enabled: false
