AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  UseCache: true

  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'Guardfile'

Gemspec/RequiredRubyVersion:
  Enabled: false
