# This is the rubocop configuration file for this gem.
# You probably shouldn't inherit from this in your own projects.
# See the [README](README.md) for instructions on using `house_style`
# style settings from within your own projects
inherit_from: ruby/rubocop.yml

Layout/IndentHeredoc:
  Exclude:
    - house_style.gemspec
